Refactor GitHub Actions Workflows and Fastlane Configuration
Details:

Workflows:

Removed the validate job dependency where unnecessary.
Adjusted needs dependencies in check_alive_and_permissions, check_latest_from_upstream, and build jobs to optimize execution order.
Consolidated redundant steps in check_certs.yml, reducing complexity.
Enhanced clarity by explicitly listing required secrets and improving step naming.
Added annotations for better debugging and user feedback during certificate operations.
Fastlane Configuration:

Changed match to disable forced certificate updates (force: false) and enabled verbose output.
Improved certificate expiration handling and logging for better feedback.
Fixed a typo in comments regarding certificate renewal flags.

diff --git a/.github/workflows/check_certs.yml b/.github/workflows/check_certs.yml
--- a/.github/workflows/check_certs.yml
+++ b/.github/workflows/check_certs.yml
@@ -4,31 +4,50 @@ run-name: Check Certificates (${{ github.ref_name }})
 on: [workflow_call, workflow_dispatch]
 
 env:
-  EXPIRATION_WARNING_DAYS: 7
+  TEAMID: ${{ secrets.TEAMID }}
+  GH_PAT: ${{ secrets.GH_PAT }}
+  GH_TOKEN: ${{ secrets.GH_PAT }}
+  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
+  FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
+  FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
+  FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
 
 jobs:
+  validate:
+    name: Validate
+    uses: ./.github/workflows/validate_secrets.yml
+    secrets: inherit
+
   check_certs:
-    runs-on: ubuntu-latest
-    env:
-      FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
-      FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
-      FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
+    needs: validate
+    runs-on: macos-14
     outputs:
       new_certificate_needed: ${{ steps.set_output.outputs.new_certificate_needed }}
 
     steps:
-      - name: Checkout repository
+      # Uncomment to manually select latest Xcode if needed
+      #- name: Select Latest Xcode
+      #  run: "sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer"
+      
+      # Checks-out the repo
+      - name: Checkout Repo
         uses: actions/checkout@v4
-
-      - name: Set up Ruby
-        uses: ruby/setup-ruby@v1
-        with:
-          ruby-version: '3.1'
-
-      - name: Install dependencies
+      
+      # Patch Fastlane Match to not print tables
+      - name: Patch Match Tables
+        run: find /usr/local/lib/ruby/gems -name table_printer.rb | xargs sed -i "" "/puts(Terminal::Table.new(params))/d"
+      
+      # Install project dependencies
+      - name: Install Project Dependencies
         run: bundle install
 
-      - name: Check Certificates and create or renew if needed
+      # Create or update provisioning profiles
+      - name: Check certificate and profiles
+        run: |
+          echo "Running Fastlane certs lane..."
+          bundle exec fastlane certs || true # ignore and continue on errors without annotating an exit code
+
+      - name: Check Distribution Certificate and create or renew if needed
         run: bundle exec fastlane check_and_renew_certificates
         id: check_certs
 
@@ -45,11 +64,6 @@ jobs:
           else
             echo "Certificate status file not found. Defaulting to false."
             echo "new_certificate_needed=false" >> $GITHUB_OUTPUT
-          fi
-
-          # Check if certs are valid
-          if [ "$CERT_STATUS" != "true" ]; then
-            echo "::notice::✅ Distribution certificate is present and valid. No action required."
           fi
 
           # Check if ENABLE_NUKE_CERTS is not set to true when certs are valid
@@ -70,54 +84,32 @@ jobs:
 
   # Nuke Certs if needed, and if the repository variable ENABLE_NUKE_CERTS is set to 'true', or if FORCE_NUKE_CERTS is set to 'true', which will always force certs to be nuked
   nuke_certs:
-    needs: check_certs
-    runs-on: macos-14
-    if: ${{ (needs.check_certs.outputs.new_certificate_needed == 'true' && vars.ENABLE_NUKE_CERTS == 'true') || vars.FORCE_NUKE_CERTS == 'true' }}
-    steps:
-      - name: Debug check_certs output
-        run: echo "new_certificate_needed=${{ needs.check_certs.outputs.new_certificate_needed }}"
+      needs: [validate, check_certs]
+      runs-on: macos-14
+      if: ${{ (needs.check_certs.outputs.new_certificate_needed == 'true' && vars.ENABLE_NUKE_CERTS == 'true') || vars.FORCE_NUKE_CERTS == 'true' }}
+      steps:
+        - name: Output from Check_certs
+          run: echo "new_certificate_needed=${{ needs.check_certs.outputs.new_certificate_needed }}"
 
-      - name: Checkout repository
-        uses: actions/checkout@v4
+        - name: Checkout repository
+          uses: actions/checkout@v4
 
-      - name: Set up Ruby
-        uses: ruby/setup-ruby@v1
-        with:
-          ruby-version: '3.1'
+        - name: Install dependencies
+          run: bundle install
 
-      - name: Install dependencies
-        run: bundle install
+        - name: Run Fastlane nuke_certs
+          run: |
+            set -e
+            bundle exec fastlane nuke_certs
 
-      - name: Run Fastlane nuke_certs
-        run: bundle exec fastlane nuke_certs
-        env:
-          TEAMID: ${{ secrets.TEAMID }}
-          GH_PAT: ${{ secrets.GH_PAT }}
-          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
-          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
-          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
-          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
-          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
-          FASTLANE_SKIP_ALL_LANE_SUMMARIES: "true"
+        - name: Recreate Distribution certificate after nuking
+          run: |
+            set -e
+            bundle exec fastlane certs
 
-      - name: Annotate Summary after Nuke
-        run: |
-          echo "::warning::⚠️⚠️⚠️   All Distribution certificates and TestFlight profiles have been revoked."
-    
-
-  # Trigger create_certs.yml if nuke_certs ran
-  trigger_create_certs:
-    needs: [check_certs, nuke_certs]
-    uses: ./.github/workflows/create_certs.yml
-    secrets: inherit
-
-  # Annotate Summary after Certificate Creation
-  annotate_summary:
-    needs: trigger_create_certs
-    runs-on: ubuntu-latest
-    steps:
-      - name: Annotate Summary
-        run: |
-          echo "::warning::⚠️⚠️⚠️   Certificates have been recreated successfully."
-          echo "::warning::⚠️⚠️⚠️   If you have other apps being distributed by GitHub Actions / Fastlane / TestFlight, please run the '3. Create Certificates' workflow for each of these apps to allow these apps to be built."
-          echo "::warning::✅✅✅   But don't worry about your existing TestFlight builds, they will keep working!"
+        - name: Add success annotations for nuke and certificate recreation
+          if: ${{ success() }}
+          run: |
+            echo "::warning::⚠️ All Distribution certificates and TestFlight profiles have been revoked and recreated."
+            echo "::warning::❗️ If you have other apps being distributed by GitHub Actions / Fastlane / TestFlight that does not renew certificates automatically, please run the '3. Create Certificates' workflow for each of these apps to allow these apps to be built."
+            echo "::warning::✅ But don't worry about your existing TestFlight builds, they will keep working!"
