test main to dev

diff --git a/.github/workflows/create_certs.yml b/.github/workflows/create_certs.yml
--- a/.github/workflows/create_certs.yml
+++ b/.github/workflows/create_certs.yml
@@ -8,7 +8,7 @@ jobs:
     name: Validate
     uses: ./.github/workflows/validate_secrets.yml
     secrets: inherit
-  
+
   certificates:
     name: Create Certificates
     needs: validate
@@ -17,15 +17,22 @@ jobs:
       # Uncomment to manually select latest Xcode if needed
       #- name: Select Latest Xcode
       #  run: "sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer"
-      
+
       # Checks-out the repo
       - name: Checkout Repo
         uses: actions/checkout@v4
-      
+
       # Patch Fastlane Match to not print tables
       - name: Patch Match Tables
-        run: find /usr/local/lib/ruby/gems -name table_printer.rb | xargs sed -i "" "/puts(Terminal::Table.new(params))/d"
-      
+        run: |
+          TABLE_PRINTER_PATH=$(ruby -e 'puts Gem::Specification.find_by_name("fastlane").gem_dir')/match/lib/match/table_printer.rb
+          if [ -f "$TABLE_PRINTER_PATH" ]; then
+            sed -i "" "/puts(Terminal::Table.new(params))/d" "$TABLE_PRINTER_PATH"
+          else
+            echo "table_printer.rb not found"
+            exit 1
+          fi
+
       # Install project dependencies
       - name: Install Project Dependencies
         run: bundle install
@@ -33,7 +40,7 @@ jobs:
       # Sync the GitHub runner clock with the Windows time server (workaround as suggested in https://github.com/actions/runner/issues/2996)
       - name: Sync clock
         run: sudo sntp -sS time.windows.com
-      
+
       # Create or update certificates for app
       - name: Create Certificates
         run: bundle exec fastlane certs
