validate_secrets.yml: Set pipefail option so that fastlane exit codes are handled correctly

diff --git a/.github/workflows/validate_secrets.yml b/.github/workflows/validate_secrets.yml
--- a/.github/workflows/validate_secrets.yml
+++ b/.github/workflows/validate_secrets.yml
@@ -94,6 +94,9 @@ jobs:
             echo "::error::The MATCH_PASSWORD secret is unset or empty. Set it and try again."
           fi
           
+          # Ensure that fastlane exit codes are handled when output is piped.
+          set -o pipefail
+          
           # Validate FASTLANE_ISSUER_ID, FASTLANE_KEY_ID, and FASTLANE_KEY
           FASTLANE_KEY_ID_PATTERN='^[A-Z0-9]+$'
           FASTLANE_ISSUER_ID_PATTERN='^\{?[A-F0-9a-f]{8}-[A-F0-9a-f]{4}-[A-F0-9a-f]{4}-[A-F0-9a-f]{4}-[A-F0-9a-f]{12}\}?$'
@@ -116,10 +119,11 @@ jobs:
             failed=true
             echo "::error::The FASTLANE_KEY secret is set but invalid. Verify that it is set correctly and try again."
           elif ! fastlane validate_secrets 2>&1 | tee fastlane.log; then
-            failed=true
             if grep -q "bad decrypt" fastlane.log; then
+              failed=true
               echo "::error::Unable to decrypt the Match-Secrets repository using the MATCH_PASSWORD secret. Verify that it is set correctly and try again."
-            else
+            elif ! grep -q "No code signing identity found" fastlane.log; then
+              failed=true
               echo "::error::Unable to create a valid authorization token for the App Store Connect API.\
               Verify that the FASTLANE_ISSUER_ID, FASTLANE_KEY_ID, and FASTLANE_KEY secrets are set correctly and try again."
             fi
