validate_secrets.yml: Rewrite GH_PAT validation to capture scopes and distinguish between classic and fine-grained access tokens

diff --git a/.github/workflows/validate_secrets.yml b/.github/workflows/validate_secrets.yml
--- a/.github/workflows/validate_secrets.yml
+++ b/.github/workflows/validate_secrets.yml
@@ -12,14 +12,44 @@ jobs:
     steps:
       - name: Validate Access Token
         run: |
+          # Validate Access Token
+          
+          # Ensure that gh exit codes are handled when output is piped.
+          set -o pipefail
+          
+          # Define patterns to validate the access token (GH_PAT) and distinguish between classic and fine-grained tokens.
+          GH_PAT_CLASSIC_PATTERN='^ghp_[a-zA-Z0-9]{36}$'
+          GH_PAT_FINE_GRAINED_PATTERN='^github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59}$'
+
           # Validate Fastlane Access Token (GH_PAT)
           if [ -z "$GH_PAT" ]; then
             failed=true
             echo "::error::The GH_PAT secret is unset or empty. Set it and try again."
-          elif [ "$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository_owner }}/LoopWorkspace | jq --raw-output '.permissions.push')" != "true" ]; then
+          elif [[ $GH_PAT =~ $GH_PAT_FINE_GRAINED_PATTERN ]]; then
+            echo "The 'GH_PAT' secret is a structurally valid fine-grained token."
+            
+            if ! curl -sS -f -o /dev/null -H "Authorization: token $GH_PAT" https://api.github.com; then
+              failed=true;
+              echo "::error::Unable to connect to GitHub using the GH_PAT secret. Verify that it is set correctly and try again."
+            fi
+          elif [[ $GH_PAT =~ $GH_CLASSIC_PATTERN ]]; then
+            echo "The 'GH_PAT' secret is a structurally valid classic token. Validating permission scopes..."
+            
+            # Capture the x-oauth-scopes scopes of the token.
+            if ! scopes=$(curl -sS -f -I -H "Authorization: token $GH_PAT" https://api.github.com | grep -i '^x-oauth-scopes:' | cut -d ' ' -f2-); then
+              failed=true
+              echo "::error::Unable to connect to GitHub using the GH_PAT secret. Verify that it is set correctly and try again."
+            elif [[ $scope =~ workflow ]]; then
+              echo "The GH_PAT secret has repo and workflow permissions."
+            elif [[ $scope =~ repo ]]; then
+              echo "The GH_PAT secret has repo (but not workflow) permissions."
+            else
+              failed=true
+              echo "::error::The GH_PAT secret is lacking at least the 'repo' permission scope required to access the Match-Secrets repository. Update the token permissions at https://github.com/settings/tokens (to include the 'repo' and 'workflow' scopes) and try again."
+            fi
+          else
             failed=true
-            echo "::error::The GH_PAT secret is set but invalid or lacking at least 'repo' permission scope ('repo, workflow' is okay too).\
-            Verify that token permissions are set correctly (or update them) at https://github.com/settings/tokens and try again."
+            echo "::error::The GH_PAT secret is set but invalid. Verify that it is set correctly (including the 'ghp_' or 'github_pat_' prefix) and try again."
           fi
           
           # Exit unsuccessfully if secret validation failed.
