validate_secrets.yml: Depend less on patterns / read scopes from any token that provides them
* Provide HAS_WORKFLOW_PERMISSION as an output

diff --git a/.github/workflows/validate_secrets.yml b/.github/workflows/validate_secrets.yml
--- a/.github/workflows/validate_secrets.yml
+++ b/.github/workflows/validate_secrets.yml
@@ -9,8 +9,11 @@ jobs:
     env:
       GH_PAT: ${{ secrets.GH_PAT }}
       GH_TOKEN: ${{ secrets.GH_PAT }}
+    outputs:
+      HAS_WORKFLOW_PERMISSION: ${{ steps.access-token.outputs.has_workflow_permission }}
     steps:
       - name: Validate Access Token
+        id: access-token
         run: |
           # Validate Access Token
           
@@ -20,36 +23,42 @@ jobs:
           # Define patterns to validate the access token (GH_PAT) and distinguish between classic and fine-grained tokens.
           GH_PAT_CLASSIC_PATTERN='^ghp_[a-zA-Z0-9]{36}$'
           GH_PAT_FINE_GRAINED_PATTERN='^github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59}$'
-
-          # Validate Fastlane Access Token (GH_PAT)
+          
+          # Validate Access Token (GH_PAT)
           if [ -z "$GH_PAT" ]; then
             failed=true
             echo "::error::The GH_PAT secret is unset or empty. Set it and try again."
-          elif [[ $GH_PAT =~ $GH_PAT_FINE_GRAINED_PATTERN ]]; then
-            echo "The 'GH_PAT' secret is a structurally valid fine-grained token."
-            
-            if ! curl -sS -f -o /dev/null -H "Authorization: token $GH_PAT" https://api.github.com; then
-              failed=true;
-              echo "::error::Unable to connect to GitHub using the GH_PAT secret. Verify that it is set correctly and try again."
-            fi
-          elif [[ $GH_PAT =~ $GH_CLASSIC_PATTERN ]]; then
-            echo "The 'GH_PAT' secret is a structurally valid classic token. Validating permission scopes..."
-            
-            # Capture the x-oauth-scopes scopes of the token.
-            if ! scopes=$(curl -sS -f -I -H "Authorization: token $GH_PAT" https://api.github.com | grep -i '^x-oauth-scopes:' | cut -d ' ' -f2-); then
-              failed=true
-              echo "::error::Unable to connect to GitHub using the GH_PAT secret. Verify that it is set correctly and try again."
-            elif [[ $scope =~ workflow ]]; then
-              echo "The GH_PAT secret has repo and workflow permissions."
-            elif [[ $scope =~ repo ]]; then
-              echo "The GH_PAT secret has repo (but not workflow) permissions."
-            else
-              failed=true
-              echo "::error::The GH_PAT secret is lacking at least the 'repo' permission scope required to access the Match-Secrets repository. Update the token permissions at https://github.com/settings/tokens (to include the 'repo' and 'workflow' scopes) and try again."
-            fi
           else
-            failed=true
-            echo "::error::The GH_PAT secret is set but invalid. Verify that it is set correctly (including the 'ghp_' or 'github_pat_' prefix) and try again."
+            if [[ $GH_PAT =~ $GH_PAT_CLASSIC_PATTERN ]]; then
+              provides_scopes=true
+              echo "The GH_PAT secret is a structurally valid classic token."
+            elif [[ $GH_PAT =~ $GH_PAT_FINE_GRAINED_PATTERN ]]; then
+              echo "The GH_PAT secret is a structurally valid fine-grained token."
+            else
+              echo "The GH_PAT secret does not have a known token format."
+            fi
+
+            # Attempt to capture the x-oauth-scopes scopes of the token.
+            if ! scopes=$(curl -sS -f -I -H "Authorization: token $GH_PAT" https://api.github.com | { grep -i '^x-oauth-scopes:' || true; } | cut -d ' ' -f2- | tr -d '\r'); then
+              failed=true
+              echo "::error::Unable to connect to GitHub using the GH_PAT secret. Verify that it is set correctly and try again."
+            elif [[ $scopes =~ workflow ]]; then
+              echo "The GH_PAT secret has repo and workflow permissions."
+              echo "has_workflow_permission=true" >> $GITHUB_OUTPUT
+            elif [[ $scopes =~ repo ]]; then
+              echo "The GH_PAT secret has repo (but not workflow) permissions."
+            elif [ $provides_scopes ]; then
+              failed=true
+              if [ -z "$scopes" ]; then
+                echo "The GH_PAT secret is valid and can be used to connect to GitHub, but it does not provide any permission scopes."
+              else
+                echo "The GH_PAT secret is valid and can be used to connect to GitHub, but it only provides the following permission scopes: $scopes"
+              fi
+              echo "::error::The GH_PAT secret is lacking at least the 'repo' permission scope required to access the Match-Secrets repository. Update the token permissions at https://github.com/settings/tokens (to include the 'repo' and 'workflow' scopes) and try again."
+            else
+              echo "The GH_PAT secret is valid and can be used to connect to GitHub, but it does not provide inspectable scopes. Assuming that the 'repo' and 'workflow' permission scopes required to access the Match-Secrets repository and perform automations are present."
+              echo "has_workflow_permission=true" >> $GITHUB_OUTPUT
+            fi
           fi
           
           # Exit unsuccessfully if secret validation failed.
@@ -97,7 +106,7 @@ jobs:
   
   validate-fastlane-secrets:
     name: Fastlane
-    needs: validate-match-secrets
+    needs: [validate-access-token, validate-match-secrets]
     runs-on: macos-13
     env:
       GH_PAT: ${{ secrets.GH_PAT }}
